spring:
  application:
    name: account

  data:
    mongodb:
      host: localhost
      port: 27017
      database: account_db


 #  data:
 #    mongodb:
#      uri: mongodb://localhost:27017/airecommendationfitness
#      database: airecommendationfitness
