account:
  msg: Welcome to Bank Account Prod application
  build-version: 3.0.0

  mailDetails:
    hostName: Prod-accounts@bank.com
    port: 9000
    from: Prod-accounts@bank.com
    subject: Your Account Details from Bank Prod Environment

  activeBranches:
    - Kep
    - Kandal
    - Kampong Thom