spring:
  application:
    name: loan

  config:
    import: optional:configserver:http://localhost:8071

  data:
    mongodb:
      uri: mongodb://localhost:27017/loan_db

server:
      port: 8090

management:
  endpoints:
    web:
      exposure:
          include: "*"
  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/

info:
  app:
    name: Loan Microservice
    description: This microservice handles loan processing and management.
    version: 1.0.0
    env:
      enabled: true


