spring:
  application:
    name: configserver

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
            uri: https://github.com/ImRady/ConfigServer
            clone-on-start: true
            default-label: main
#        native:
#          search-locations: classpath:/config
#           search-locations: file:///E://bank/config-repo/

server:
    port: 8071